### ISSUE TITLE
webhook channel

### ISSUE THREAD

**Issue by odra** [odra/sumatraproject#6]
## Feature Description:

Implement a webhook channel type in the "channels" module so non default integrations are supported, suggested format:

```yaml
name: something
type: webhook
spec:
  url: http://myurl.com/path
  verb: POST #defaults to POST if omitted
  body: "something" #optional (string format)
  headers: {} #optional extra headers expressed in in a dict (key:value) format
  expected_code: 200 #optional and defaults to 200 if omitted
```
